spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: product
          uri: http://localhost:8081
          predicates:
            - Path=/products/**